apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-api-pod-node-id
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:aveeva-devops/projects.git
    targetRevision: HEAD
    path: kubernetes/EKS-ArgoCD/app2
  destination: 
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true