apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]  # Keeps the pod running for an hour
      resources:
        limits:
          cpu: "0.1"
          memory: "128Mi"
        requests:
          cpu: "0.05"
          memory: "64Mi"
  restartPolicy: Always